[package]
name = "reddit-refresh-online"
version = "0.1.0"
authors = ["Nicholas <dojoman19@gmail.com>"]

[dependencies]
rocket = "0.3.12"
rocket_codegen = "0.3.12"
reqwest = "0.8.6"
serde_json = "1.0.19"
cookie = "0.9.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]